### ISSUE TITLE
xxx/seeyon/testW12345.jsp是webshell吗？

### ISSUE THREAD

**Issue by fishmisswater** [Anonymous-ghost/AttackWebFrameworkTools#11]
密码是多少？

**Comment by Anonymous-ghost** [comment]
这个是webshell 是一个上传马 参数 htttp://www.xxx.com/x.jsp?f=ma.jsp  postData:t=木马内容

**Comment by Anonymous-ghost** [comment]
后续如果遇到waf使用明文传输或者f参数被拦截请私信附且带目标url。我会更新上述网马。感谢提交Issue

**Comment by fishmisswater** [comment]
具体怎么用呢？
我requests.post(xxx/seeyon/testW12345.jsp?f=ma.jsp,data={"t":"一句话"} ) 或者put，都是返回的404

**Comment by Anonymous-ghost** [comment]
木马地址私发一下我看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月13日(周二) 上午10:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)




 
具体怎么用呢？
 我requests.post(xxx/seeyon/testW12345.jsp?f=ma.jsp,data={"t":"一句话"} ) 或者put，都是返回的404

**Comment by fishmisswater** [comment]
表哥好，下面的都不知道怎么利用
http://222.239.225.92:80/seeyon/testW12345.jsp
https://3.108.71.46:8443/seeyon/testW12345.jsp
|http://106.10.33.251/trace|http://106.10.33.251/env|http://106.10.33.251/health|http://106.10.33.251/refresh|http://106.10.33.251/autoconfig|http://106.10.33.251/info|http://106.10.33.251/httptrace
http://112.186.63.133|postData:admin:KYLIN




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)





 木马地址私发一下我看看 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年7月13日(周二) 上午10:35 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11) 
 
 
 
 
   
 具体怎么用呢？ 
  我requests.post(xxx/seeyon/testW12345.jsp?f=ma.jsp,data={"t":"一句话"} ) 或者put，都是返回的404

**Comment by Anonymous-ghost** [comment]
你这用什么参数扫描的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)





 表哥好，下面的都不知道怎么利用 
 http://222.239.225.92:80/seeyon/testW12345.jsp 
 https://3.108.71.46:8443/seeyon/testW12345.jsp 
 |http://106.10.33.251/trace|http://106.10.33.251/env|http://106.10.33.251/health|http://106.10.33.251/refresh|http://106.10.33.251/autoconfig|http://106.10.33.251/info|http://106.10.33.251/httptrace 
 http://112.186.63.133|postData:admin:KYLIN 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年7月13日(星期二) 上午10:37 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11) 
 
 
 
 
 
  木马地址私发一下我看看  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2021年7月13日(周二) 上午10:35  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)  
   
   
   
   
     
  具体怎么用呢？  
   我requests.post(xxx/seeyon/testW12345.jsp?f=ma.jsp,data={"t":"一句话"} ) 或者put，都是返回的404

**Comment by fishmisswater** [comment]
.\AttackWebFrameworkTools.exe -thread 50
没用啥参数呀


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 上午10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)





 你这用什么参数扫描的 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年7月13日(星期二) 上午10:43 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11) 
 
 
 
 
 
  表哥好，下面的都不知道怎么利用  
  http://222.239.225.92:80/seeyon/testW12345.jsp  
  https://3.108.71.46:8443/seeyon/testW12345.jsp  
  |http://106.10.33.251/trace|http://106.10.33.251/env|http://106.10.33.251/health|http://106.10.33.251/refresh|http://106.10.33.251/autoconfig|http://106.10.33.251/info|http://106.10.33.251/httptrace  
  http://112.186.63.133|postData:admin:KYLIN  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年7月13日(星期二) 上午10:37  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)  
   
   
   
   
   
   木马地址私发一下我看看   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2021年7月13日(周二) 上午10:35   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.***&amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;gt;;   
   主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)   
     
     
     
     
       
   具体怎么用呢？   
    我requests.post(xxx/seeyon/testW12345.jsp?f=ma.jsp,data={"t":"一句话"} ) 或者put，都是返回的404

**Comment by Anonymous-ghost** [comment]
这个seeyon OA 有误报。。。这些都不存在完了我修复一下。扫描的时候最好要带参数




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)





 .\AttackWebFrameworkTools.exe -thread 50 
 没用啥参数呀 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月13日(星期二) 上午10:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11) 
 
 
 
 
 
  你这用什么参数扫描的  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年7月13日(星期二) 上午10:43  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; "State ***@***.***&amp;amp;gt;;   
  主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)  
   
   
   
   
   
   表哥好，下面的都不知道怎么利用   
   http://222.239.225.92:80/seeyon/testW12345.jsp   
   https://3.108.71.46:8443/seeyon/testW12345.jsp   
   |http://106.10.33.251/trace|http://106.10.33.251/env|http://106.10.33.251/health|http://106.10.33.251/refresh|http://106.10.33.251/autoconfig|http://106.10.33.251/info|http://106.10.33.251/httptrace   
   http://112.186.63.133|postData:admin:KYLIN   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2021年7月13日(星期二) 上午10:37   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)   
     
     
     
     
     
    木马地址私发一下我看看    
       
       
       
    ---原始邮件---    
    发件人: ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2021年7月13日(周二) 上午10:35    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;    
    抄送: ***@***.***&amp;amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;amp;gt;;    
    主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)    
       
       
       
       
         
    具体怎么用呢？    
     我requests.post(xxx/seeyon/testW12345.jsp?f=ma.jsp,data={"t":"一句话"} ) 或者put，都是返回的404

**Comment by Anonymous-ghost** [comment]
***@***.***。在git上发挥泄露的目标地址!!!!。感谢提交让我发下软件三处存在误报。这周更新解决误报问题!!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 上午10:54
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)





 .\AttackWebFrameworkTools.exe -thread 50 
 没用啥参数呀 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月13日(星期二) 上午10:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11) 
 
 
 
 
 
  你这用什么参数扫描的  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年7月13日(星期二) 上午10:43  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; "State ***@***.***&amp;amp;gt;;   
  主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)  
   
   
   
   
   
   表哥好，下面的都不知道怎么利用   
   http://222.239.225.92:80/seeyon/testW12345.jsp   
   https://3.108.71.46:8443/seeyon/testW12345.jsp   
   |http://106.10.33.251/trace|http://106.10.33.251/env|http://106.10.33.251/health|http://106.10.33.251/refresh|http://106.10.33.251/autoconfig|http://106.10.33.251/info|http://106.10.33.251/httptrace   
   http://112.186.63.133|postData:admin:KYLIN   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2021年7月13日(星期二) 上午10:37   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)   
     
     
     
     
     
    木马地址私发一下我看看    
       
       
       
    ---原始邮件---    
    发件人: ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2021年7月13日(周二) 上午10:35    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;    
    抄送: ***@***.***&amp;amp;amp;amp;gt;;"State ***@***.***&amp;amp;amp;amp;gt;;    
    主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] xxx/seeyon/testW12345.jsp是webshell吗？ (#11)    
       
       
       
       
         
    具体怎么用呢？    
     我requests.post(xxx/seeyon/testW12345.jsp?f=ma.jsp,data={"t":"一句话"} ) 或者put，都是返回的404
