### ISSUE TITLE
优化一下检验算法吧

### ISSUE THREAD

**Issue by EASY233** [Anonymous-ghost/AttackWebFrameworkTools#5]
这个正确率简直了，随便拿来的几个网站也能全部检测出来漏洞，经过我的手工检测全部为误报
![image](https://user-images.githubusercontent.com/48321348/115483197-e8cb0700-a282-11eb-9e5e-3fc46c6ddbc2.png)
![image](https://user-images.githubusercontent.com/48321348/115483311-1d3ec300-a283-11eb-9c18-7f5b934bba6e.png)

**Comment by Anonymous-ghost** [comment]
误报是那几个参数漏洞网址发一个我看看私发到我邮箱

**Comment by EASY233** [comment]
部分ip涉及到内网无法发给你测试，只发在外网的
我直接把在外网的扫描结果发给你
和信下一代云桌面VENGD上传|http://59.69.128.67/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart
和信下一代云桌面VENGD上传|http://59.69.128.67/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart
和信下一代云桌面VENGD上传|http://59.69.128.120/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart

锐捷网络-EWEB网管系统未授权getshell |http://59.69.128.56/guest_auth/sxfRuijie.php|X
Apache AcitveMQ login Success!!!|https://59.69.128.17|admin:admin
锐捷网络-EWEB网管系统未授权getshell |http://59.69.128.56:80/guest_auth/sxfRuijie.php|X
Apache AcitveMQ login Success!!!|https://59.69.128.17:443|admin:admin
Apache AcitveMQ login Success!!!|http://59.69.128.80:80|admin:admin









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月21日(星期三) 上午9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] 优化一下检验算法吧 (#5)





 
误报是那几个参数漏洞网址发一个我看看私发到我邮箱

**Comment by Anonymous-ghost** [comment]
Ok下次更新优化一下。感谢提供建议



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月21日(周三) 上午9:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] 优化一下检验算法吧 (#5)




 部分ip涉及到内网无法发给你测试，只发在外网的 
 我直接把在外网的扫描结果发给你 
 和信下一代云桌面VENGD上传|http://59.69.128.67/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart 
 和信下一代云桌面VENGD上传|http://59.69.128.67/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart 
 和信下一代云桌面VENGD上传|http://59.69.128.120/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart 
 
 锐捷网络-EWEB网管系统未授权getshell |http://59.69.128.56/guest_auth/sxfRuijie.php|X 
 Apache AcitveMQ login Success!!!|https://59.69.128.17|admin:admin 
 锐捷网络-EWEB网管系统未授权getshell |http://59.69.128.56:80/guest_auth/sxfRuijie.php|X 
 Apache AcitveMQ login Success!!!|https://59.69.128.17:443|admin:admin 
 Apache AcitveMQ login Success!!!|http://59.69.128.80:80|admin:admin 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年4月21日(星期三) 上午9:26 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] 优化一下检验算法吧 (#5) 
 
 
 
 
 
   
 误报是那几个参数漏洞网址发一个我看看私发到我邮箱

**Comment by EASY233** [comment]
加油




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月21日(星期三) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] 优化一下检验算法吧 (#5)





 Ok下次更新优化一下。感谢提供建议 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年4月21日(周三) 上午9:38 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Anonymous-ghost/AttackWebFrameworkTools] 优化一下检验算法吧 (#5) 
 
 
 
 
  部分ip涉及到内网无法发给你测试，只发在外网的  
  我直接把在外网的扫描结果发给你  
  和信下一代云桌面VENGD上传|http://59.69.128.67/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart  
  和信下一代云桌面VENGD上传|http://59.69.128.67/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart  
  和信下一代云桌面VENGD上传|http://59.69.128.120/Upload/upload_file.php?l=../vesystem/|MultiPartData postData:Multipart  
   
  锐捷网络-EWEB网管系统未授权getshell |http://59.69.128.56/guest_auth/sxfRuijie.php|X  
  Apache AcitveMQ login Success!!!|https://59.69.128.17|admin:admin  
  锐捷网络-EWEB网管系统未授权getshell |http://59.69.128.56:80/guest_auth/sxfRuijie.php|X  
  Apache AcitveMQ login Success!!!|https://59.69.128.17:443|admin:admin  
  Apache AcitveMQ login Success!!!|http://59.69.128.80:80|admin:admin  
   
   
   
   
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "Anonymous-ghost/AttackWebFrameworkTools"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年4月21日(星期三) 上午9:26  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [Anonymous-ghost/AttackWebFrameworkTools] 优化一下检验算法吧 (#5)  
   
   
   
   
   
     
  误报是那几个参数漏洞网址发一个我看看私发到我邮箱
