### ISSUE TITLE
和信下一代云桌面上传存在误报

### ISSUE THREAD

**Issue by TryA9ain** [Anonymous-ghost/AttackWebFrameworkTools#6]
![image](https://user-images.githubusercontent.com/51145610/115958007-1a202d00-a538-11eb-8cb2-70dc437acee0.png)
tomcat的jsp网站扫出来了php的点。。。

**Comment by Anonymous-ghost** [comment]
这个maybevul绝对有误报。可以把网址私发我。在争取误报小的基础上减少漏报率



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月24日(周六) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Anonymous-ghost/AttackWebFrameworkTools] 和信下一代云桌面上传存在误报 (#6)




 

 tomcat的jsp网站扫出来了php的点。。。

**Comment by TryA9ain** [comment]
> 这个maybevul绝对有误报。如果可以的话把网址私发我。在争取误报小的基础上减少漏报率。注意看软件介绍。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年4月24日(周六) 晚上8:05 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Anonymous-ghost/AttackWebFrameworkTools] 和信下一代云桌面上传存在误报 (#6) tomcat的jsp网站扫出来了php的点。。。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Anonymous-ghost** [comment]
请下载新版本新版已经修复!!!!
