### ISSUE TITLE
diaoyu

### ISSUE THREAD

**Issue by lonelywolfcbr** [Anonymous-ghost/AttackWebFrameworkTools#9]
diaoyu

**Comment by Anonymous-ghost** [comment]
无关软件问题请不要留言

**Comment by lonelywolfcbr** [comment]
改过时间无法运行且报毒,沙箱检测are you sure?

**Comment by Anonymous-ghost** [comment]
你在沙箱运行。你觉得你能改沙箱的时间么。。。。修改本地时间肯定能运行。看git介绍



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 8, 2021 22:50 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Anonymous-ghost/AttackWebFrameworkTools] diaoyu (#9)




 
改过时间无法运行且报毒,沙箱检测are you sure?

**Comment by lonelywolfcbr** [comment]
您好.虚拟机改时间无法运行，压缩包时间为5.23.已经改过了

**Comment by Anonymous-ghost** [comment]
实体机运行没毒放心。可能强壳检测虚拟机



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 8, 2021 23:08 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Anonymous-ghost/AttackWebFrameworkTools] diaoyu (#9)




 
您好.虚拟机改时间无法运行，压缩包时间为5.23.已经改过了

**Comment by lonelywolfcbr** [comment]
还是不行 ...

**Comment by lonelywolfcbr** [comment]
从5月15日 5月23 6月1日 6月3 今天 明天都试过了

**Comment by lonelywolfcbr** [comment]
一定是哪里出现了问题...唉

**Comment by Anonymous-ghost** [comment]
你姿势问题。。。。。。。。。仔细看github软件使用说明。。。。。别人是爆毒你是软件打不开加爆毒你是人才。。



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 8, 2021 23:32 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Anonymous-ghost/AttackWebFrameworkTools] diaoyu (#9)




 
还是不行 ...

**Comment by Anonymous-ghost** [comment]
等我身体恢复以后再看吧最近电脑不在身边。你等着吧。。如果解决不了



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 8, 2021 23:32 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Anonymous-ghost/AttackWebFrameworkTools] diaoyu (#9)




 
从5月15日 5月23 6月1日 6月3 今天 明天都试过了
